# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0011_auto_20170307_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
