# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0003_delete_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('address', models.TextField(default='')),
                ('date', models.DateTimeField()),
                ('contact', models.CharField(default='', max_length=25)),
                ('district', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='address.District')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
