# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camp', '0004_auto_20170322_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='rrc',
        ),
        migrations.AddField(
            model_name='camp',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
