# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrc', '0010_rrc_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rrc',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.District'),
        ),
    ]
