# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20170213_0924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
    ]
