# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood', '0001_initial'),
        ('address', '0003_delete_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=25)),
                ('particulars', models.TextField(null=True)),
                ('units', models.IntegerField()),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('date_of_request', models.DateTimeField()),
                ('blood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.Blood')),
                ('district', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='address.District')),
            ],
        ),
    ]
